/* ==============================================================
   leaderboard.js
   Reusable leaderboard frontend — data-driven, JSON-backed.

   HOW TO ADD A NEW ASSIGNMENT
   ----------------------------------------------------------------
   1. Create a new JSON file in /data (copy the schema of an
      existing one, e.g. data/assignment1.json).
   2. Add one line to the ASSIGNMENTS config below pointing the
      new assignment id at that file.
   That's it — nothing else in this file needs to change.

   HOW TO UPDATE AN EXISTING LEADERBOARD
   ----------------------------------------------------------------
   Edit the corresponding JSON file in /data:
     - update "entries" (rollNo, ndcg, map, indexSize, buildTime,
       queryLatency)
     - update "lastUpdated"
   Do NOT edit this file for a routine leaderboard update. Index
   size score and the efficiency adjustment are DERIVED here from
   the raw indexSize / buildTime / queryLatency values — never
   type a pre-computed efficiency number into the JSON.
   ============================================================== */

// ----------------------------------------------------------------
// 1. Assignment configuration — the only place that maps an
//    assignment to its data file. Keep this separate from scores.
// ----------------------------------------------------------------
const ASSIGNMENTS = {
  assignment1: { label: "Assignment 1", file: "data/assignment1.json" },
  assignment2: { label: "Assignment 2", file: "data/assignment2.json" },
  // assignment3: { label: "Assignment 3", file: "data/assignment3.json" },
};

const DEFAULT_ASSIGNMENT = "assignment1";

// ----------------------------------------------------------------
// Scoring policy (per the assignment spec):
//   Final Score = 70% nDCG@10
//               + 10% MAP@10
//               + Index Size score (0 to 10%)
//               + Efficiency adjustment (±10%)
//
// Index Size score (out of WEIGHT_INDEX_SIZE):
//   - full marks  when indexSize <= 0.5 * classMedianIndexSize
//   - zero marks  when indexSize >= 2.0 * classMedianIndexSize
//   - linear interpolation between those two points
//
// Efficiency adjustment (±EFFICIENCY_MAX):
//   - combinedTime = buildTime (s) + queryLatency (ms) / 1000
//     (index build time plus mean query latency, same units)
//   - classMedianCombinedTime = median(combinedTime) across the
//     assignment's submissions
//   - deviation = (median - combinedTime) / median
//     (positive => faster than the class median => bonus)
//   - efficiency = clamp(deviation, -1, +1) * EFFICIENCY_MAX
//     i.e. a submission at 0x the median time gets the full +10%,
//     a submission at 2x (or worse) the median time gets the full
//     -10%, and it's linear in between, centered on 0 at the median.
// ----------------------------------------------------------------
const WEIGHT_NDCG = 0.70;
const WEIGHT_MAP = 0.10;
const WEIGHT_INDEX_SIZE = 0.10;
const EFFICIENCY_MAX = 0.10;

// Holds the currently rendered leaderboard so the download buttons
// always export exactly what's on screen.
let currentState = null; // { assignmentId, assignmentTitle, lastUpdated, entries }

// ----------------------------------------------------------------
// 2. Data loading — isolated so it can later be swapped for a
//    real API/database call without touching scoring or rendering.
// ----------------------------------------------------------------
async function loadLeaderboardData(source) {
  const response = await fetch(source, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`Failed to load "${source}" (HTTP ${response.status})`);
  }
  const data = await response.json();
  if (!data || !Array.isArray(data.entries)) {
    throw new Error(`Malformed leaderboard data in "${source}"`);
  }
  return data;
}

// ----------------------------------------------------------------
// 3. Scoring + ranking — pure function, no DOM access.
// ----------------------------------------------------------------
function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 !== 0
    ? sorted[mid]
    : (sorted[mid - 1] + sorted[mid]) / 2;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function indexSizeScoreFor(indexSize, classMedianIndexSize) {
  if (!classMedianIndexSize) return WEIGHT_INDEX_SIZE;

  const lowerBound = 0.5 * classMedianIndexSize; // full marks at/below this
  const upperBound = 2.0 * classMedianIndexSize; // zero marks at/above this

  if (indexSize <= lowerBound) return WEIGHT_INDEX_SIZE;
  if (indexSize >= upperBound) return 0;

  const fraction = (upperBound - indexSize) / (upperBound - lowerBound);
  return WEIGHT_INDEX_SIZE * fraction;
}

function efficiencyAdjustmentFor(combinedTime, classMedianCombinedTime) {
  if (!classMedianCombinedTime) return 0;

  const deviation = (classMedianCombinedTime - combinedTime) / classMedianCombinedTime;
  return clamp(deviation, -1, 1) * EFFICIENCY_MAX;
}

function calculateScores(entries) {
  const withCombinedTime = entries.map((row) => ({
    ...row,
    combinedTime: row.buildTime + row.queryLatency / 1000,
  }));

  const classMedianIndexSize = median(withCombinedTime.map((r) => r.indexSize));
  const classMedianCombinedTime = median(withCombinedTime.map((r) => r.combinedTime));

  const scored = withCombinedTime.map((row) => {
    const indexSizeScore = indexSizeScoreFor(row.indexSize, classMedianIndexSize);
    const efficiency = efficiencyAdjustmentFor(row.combinedTime, classMedianCombinedTime);
    const finalScore =
      WEIGHT_NDCG * row.ndcg + WEIGHT_MAP * row.map + indexSizeScore + efficiency;

    return { ...row, indexSizeScore, efficiency, finalScore };
  });

  scored.sort((a, b) => {
    if (b.finalScore !== a.finalScore) return b.finalScore - a.finalScore;
    if (b.ndcg !== a.ndcg) return b.ndcg - a.ndcg;
    return String(a.rollNo).localeCompare(String(b.rollNo), undefined, { numeric: true });
  });

  return scored.map((row, i) => ({ ...row, rank: i + 1 }));
}

// ----------------------------------------------------------------
// 4. Formatting helpers
// ----------------------------------------------------------------
function fmt4(n) {
  return Number(n).toFixed(4);
}
function fmtSize(n) {
  return `${Math.round(n)} bytes`;
}
function fmtEff(n) {
  const v = Number(n);
  if (v > 0) return `+${v.toFixed(2)}`;
  if (v < 0) return `\u2212${Math.abs(v).toFixed(2)}`; // minus sign
  return `\u00b1${v.toFixed(2)}`; // ±0.00
}
function effClass(n) {
  const v = Number(n);
  if (v > 0) return "eff-pos";
  if (v < 0) return "eff-neg";
  return "eff-zero";
}
function medalFor(rank) {
  if (rank === 1) return '<span class="medal gold">\u{1F947}</span>';
  if (rank === 2) return '<span class="medal silver">\u{1F948}</span>';
  if (rank === 3) return '<span class="medal bronze">\u{1F949}</span>';
  return `<span style="width:26px;display:inline-flex;justify-content:center;">${rank}</span>`;
}

// ----------------------------------------------------------------
// 5. Rendering — DOM updates only, takes fully-prepared data.
// ----------------------------------------------------------------
function renderLeaderboard(state) {
  currentState = state;

  document.getElementById("assignment-title").textContent = state.assignmentTitle;
  document.getElementById("updated-at").textContent = state.lastUpdated;
  document.getElementById("entry-count").textContent = state.entries.length;
  document.getElementById("panel-count").textContent = `${state.entries.length} submissions`;

  const body = document.getElementById("leaderboard-body");
  body.innerHTML = "";

  state.entries.forEach((row) => {
    const tr = document.createElement("tr");
    if (row.rank <= 3) tr.classList.add(`top${row.rank}`);

    tr.innerHTML = `
      <td data-label="Rank"><span class="rank-cell">${medalFor(row.rank)}</span></td>
      <td data-label="Roll No."><span class="roll-no ${row.rank <= 3 ? "top" : ""}">${row.rollNo}</span></td>
      <td data-label="nDCG@10">${fmt4(row.ndcg)}</td>
      <td data-label="MAP@10">${fmt4(row.map)}</td>
      <td data-label="Index Size">${fmtSize(row.indexSize)}</td>
      <td data-label="Efficiency"><span class="${effClass(row.efficiency)}">${fmtEff(row.efficiency)}</span></td>
      <td data-label="Final Score"><span class="score-cell">${fmt4(row.finalScore)}</span></td>
    `;
    body.appendChild(tr);
  });

  setStatus(null);
  setDownloadButtonsEnabled(true);
}

// ----------------------------------------------------------------
// 6. Loading / error status UI
// ----------------------------------------------------------------
function setStatus(message, isError = false) {
  const el = document.getElementById("status-message");
  if (!message) {
    el.hidden = true;
    el.textContent = "";
    return;
  }
  el.hidden = false;
  el.textContent = message;
  el.classList.toggle("status-error", isError);
}

function setDownloadButtonsEnabled(enabled) {
  document.getElementById("download-csv-btn").disabled = !enabled;
  document.getElementById("download-pdf-btn").disabled = !enabled;
}

// ----------------------------------------------------------------
// 7. Assignment switching
// ----------------------------------------------------------------
async function selectAssignment(assignmentId) {
  const config = ASSIGNMENTS[assignmentId];
  if (!config) return;

  setDownloadButtonsEnabled(false);
  setStatus("Loading leaderboard...");

  try {
    const raw = await loadLeaderboardData(config.file);
    const ranked = calculateScores(raw.entries);
    renderLeaderboard({
      assignmentId,
      assignmentTitle: raw.assignment || config.label,
      lastUpdated: raw.lastUpdated || "—",
      entries: ranked,
    });
  } catch (err) {
    console.error(err);
    setStatus("Unable to load leaderboard data.", true);
    setDownloadButtonsEnabled(false);
  }
}

// ----------------------------------------------------------------
// 8. Assignment selector — populated dynamically from ASSIGNMENTS
//    so adding a new assignment never requires touching index.html.
// ----------------------------------------------------------------
function initAssignmentSelector() {
  const select = document.getElementById("assignment-select");
  select.innerHTML = "";

  Object.entries(ASSIGNMENTS).forEach(([id, config]) => {
    const opt = document.createElement("option");
    opt.value = id;
    opt.textContent = config.label;
    select.appendChild(opt);
  });

  select.value = DEFAULT_ASSIGNMENT;
  select.addEventListener("change", (e) => selectAssignment(e.target.value));
}

// ----------------------------------------------------------------
// 9. CSV download — exports exactly what's currently rendered.
// ----------------------------------------------------------------
function csvEscape(value) {
  const str = String(value);
  if (/[",\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function downloadCSV() {
  if (!currentState) return;

  const lines = [];
  lines.push(["Assignment", currentState.assignmentTitle].map(csvEscape).join(","));
  lines.push(["Last Updated", currentState.lastUpdated].map(csvEscape).join(","));
  lines.push("");
  lines.push(
    ["Rank", "Roll No.", "nDCG@10", "MAP@10", "Index Size (MB)", "Efficiency", "Final Score"]
      .map(csvEscape)
      .join(",")
  );

  currentState.entries.forEach((row) => {
    lines.push(
      [
        row.rank,
        row.rollNo,
        fmt4(row.ndcg),
        fmt4(row.map),
        Math.round(row.indexSize),
        fmtEff(row.efficiency),
        fmt4(row.finalScore),
      ]
        .map(csvEscape)
        .join(",")
    );
  });

  const csvContent = lines.join("\r\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const filenameSafeTitle = currentState.assignmentTitle
    .replace(/[^a-z0-9]+/gi, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();

  const a = document.createElement("a");
  a.href = url;
  a.download = `${filenameSafeTitle || "leaderboard"}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ----------------------------------------------------------------
// 10. Print / Save-as-PDF — uses the browser's native print dialog
//     on a print-only stylesheet (see index.html). No backend,
//     no PDF library required.
// ----------------------------------------------------------------
function downloadPDF() {
  if (!currentState) return;

  const previousTitle = document.title;
  document.title = `${currentState.assignmentTitle} — Leaderboard`;

  window.print();

  // Restore the tab title after the print dialog closes.
  window.setTimeout(() => {
    document.title = previousTitle;
  }, 500);
}

// ----------------------------------------------------------------
// 11. Init
// ----------------------------------------------------------------
document.addEventListener("DOMContentLoaded", () => {
  initAssignmentSelector();
  document.getElementById("download-csv-btn").addEventListener("click", downloadCSV);
  document.getElementById("download-pdf-btn").addEventListener("click", downloadPDF);
  setDownloadButtonsEnabled(false);
  selectAssignment(DEFAULT_ASSIGNMENT);
});
