/* ==============================================================
   leaderboard.js
   Reusable leaderboard frontend — data-driven, JSON-backed.

   HOW TO ADD A NEW ASSIGNMENT
   ----------------------------------------------------------------
   1. Create a new JSON file in /data (copy the schema of an
      existing one, e.g. data/assignment1.json).
   2. Add one line to the ASSIGNMENTS config below pointing the
      new assignment id at that file.
   That's it — nothing else in this file needs to change.

   HOW TO UPDATE AN EXISTING LEADERBOARD
   ----------------------------------------------------------------
   Edit the corresponding JSON file in /data:
     - update "entries" (rank, student, ndcg, map, indexSize,
       efficiency, devScore)
     - update "lastUpdated"
   Do NOT edit this file for a routine leaderboard update. Scores
   are computed by the grading harness and published as a snapshot.
   ============================================================== */

// ----------------------------------------------------------------
// 1. Assignment configuration — the only place that maps an
//    assignment to its data file. Keep this separate from scores.
// ----------------------------------------------------------------
const ASSIGNMENTS = {
  phase1: { label: "Phase 1", file: "data/assignment1.json" },
  phase2: { label: "Phase 2", file: "data/assignment2.json" },
  // assignment3: { label: "Assignment 3", file: "data/assignment3.json" },
};

const DEFAULT_ASSIGNMENT = "phase2";

// Holds the currently rendered leaderboard so the download buttons
// always export exactly what's on screen.
let currentState = null; // { assignmentId, assignmentTitle, lastUpdated, entries }

// ----------------------------------------------------------------
// 2. Data loading — isolated so it can later be swapped for a
//    real API/database call without touching scoring or rendering.
// ----------------------------------------------------------------
async function loadLeaderboardData(source) {
  const response = await fetch(source, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`Failed to load "${source}" (HTTP ${response.status})`);
  }
  const data = await response.json();
  if (!data || !Array.isArray(data.entries)) {
    throw new Error(`Malformed leaderboard data in "${source}"`);
  }
  return data;
}

// ----------------------------------------------------------------
// 3. Ordering — rank and scores come from the grading snapshot.
// ----------------------------------------------------------------
function orderEntries(entries) {
  return [...entries].sort((a, b) => a.rank - b.rank);
}

// ----------------------------------------------------------------
// 4. Formatting helpers
// ----------------------------------------------------------------
function fmt4(n) {
  return Number(n).toFixed(4);
}
function fmtSize(n) {
  return `${Math.round(n)} bytes`;
}
function fmtEff(n) {
  const v = Number(n);
  if (v > 0) return `+${v.toFixed(2)}`;
  if (v < 0) return `\u2212${Math.abs(v).toFixed(2)}`; // minus sign
  return `\u00b1${v.toFixed(2)}`; // ±0.00
}
function effClass(n) {
  const v = Number(n);
  if (v > 0) return "eff-pos";
  if (v < 0) return "eff-neg";
  return "eff-zero";
}
function medalFor(rank) {
  if (rank === 1) return '<span class="medal gold">\u{1F947}</span>';
  if (rank === 2) return '<span class="medal silver">\u{1F948}</span>';
  if (rank === 3) return '<span class="medal bronze">\u{1F949}</span>';
  return `<span style="width:26px;display:inline-flex;justify-content:center;">${rank}</span>`;
}

// ----------------------------------------------------------------
// 5. Rendering — DOM updates only, takes fully-prepared data.
// ----------------------------------------------------------------
function renderLeaderboard(state) {
  currentState = state;

  document.getElementById("assignment-title").textContent = state.assignmentTitle;
  document.getElementById("dataset-description").textContent = state.description;
  document.getElementById("updated-at").textContent = state.lastUpdated;
  document.getElementById("entry-count").textContent = state.entries.length;
  document.getElementById("panel-count").textContent = `${state.entries.length} submissions`;

  const body = document.getElementById("leaderboard-body");
  body.innerHTML = "";

  state.entries.forEach((row) => {
    const tr = document.createElement("tr");
    if (row.rank <= 3) tr.classList.add(`top${row.rank}`);

    tr.innerHTML = `
      <td data-label="Rank"><span class="rank-cell">${medalFor(row.rank)}</span></td>
      <td data-label="Name"><span class="roll-no ${row.rank <= 3 ? "top" : ""}">${row.student}</span></td>
      <td data-label="nDCG@10">${fmt4(row.ndcg)}</td>
      <td data-label="MAP@10">${fmt4(row.map)}</td>
      <td data-label="Index Size">${fmtSize(row.indexSize)}</td>
      <td data-label="Efficiency"><span class="${effClass(row.efficiency)}">${fmtEff(row.efficiency)}</span></td>
      <td data-label="Dev Score"><span class="score-cell">${fmt4(row.devScore)}</span></td>
    `;
    body.appendChild(tr);
  });

  setStatus(null);
  setDownloadButtonsEnabled(true);
}

// ----------------------------------------------------------------
// 6. Loading / error status UI
// ----------------------------------------------------------------
function setStatus(message, isError = false) {
  const el = document.getElementById("status-message");
  if (!message) {
    el.hidden = true;
    el.textContent = "";
    return;
  }
  el.hidden = false;
  el.textContent = message;
  el.classList.toggle("status-error", isError);
}

function setDownloadButtonsEnabled(enabled) {
  document.getElementById("download-csv-btn").disabled = !enabled;
  document.getElementById("download-pdf-btn").disabled = !enabled;
}

// ----------------------------------------------------------------
// 7. Assignment switching
// ----------------------------------------------------------------
async function selectAssignment(assignmentId) {
  const config = ASSIGNMENTS[assignmentId];
  if (!config) return;

  setDownloadButtonsEnabled(false);
  setStatus("Loading leaderboard...");

  try {
    const raw = await loadLeaderboardData(config.file);
    const ranked = orderEntries(raw.entries);
    renderLeaderboard({
      assignmentId,
      assignmentTitle: raw.assignment || config.label,
      description: raw.description || "",
      lastUpdated: raw.lastUpdated || "—",
      entries: ranked,
    });
  } catch (err) {
    console.error(err);
    setStatus("Unable to load leaderboard data.", true);
    setDownloadButtonsEnabled(false);
  }
}

// ----------------------------------------------------------------
// 8. Assignment selector — populated dynamically from ASSIGNMENTS
//    so adding a new assignment never requires touching index.html.
// ----------------------------------------------------------------
function initAssignmentSelector() {
  const select = document.getElementById("assignment-select");
  select.innerHTML = "";

  Object.entries(ASSIGNMENTS).forEach(([id, config]) => {
    const opt = document.createElement("option");
    opt.value = id;
    opt.textContent = config.label;
    select.appendChild(opt);
  });

  select.value = DEFAULT_ASSIGNMENT;
  select.addEventListener("change", (e) => selectAssignment(e.target.value));
}

// ----------------------------------------------------------------
// 9. CSV download — exports exactly what's currently rendered.
// ----------------------------------------------------------------
function csvEscape(value) {
  const str = String(value);
  if (/[",\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function downloadCSV() {
  if (!currentState) return;

  const lines = [];
  lines.push(["Assignment", currentState.assignmentTitle].map(csvEscape).join(","));
  lines.push(["Last Updated", currentState.lastUpdated].map(csvEscape).join(","));
  lines.push("");
  lines.push(
    ["Rank", "Name", "nDCG@10", "MAP@10", "Index Size (bytes)", "Efficiency", "Dev Score"]
      .map(csvEscape)
      .join(",")
  );

  currentState.entries.forEach((row) => {
    lines.push(
      [
        row.rank,
        row.student,
        fmt4(row.ndcg),
        fmt4(row.map),
        Math.round(row.indexSize),
        fmtEff(row.efficiency),
        fmt4(row.devScore),
      ]
        .map(csvEscape)
        .join(",")
    );
  });

  const csvContent = lines.join("\r\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const filenameSafeTitle = currentState.assignmentTitle
    .replace(/[^a-z0-9]+/gi, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();

  const a = document.createElement("a");
  a.href = url;
  a.download = `${filenameSafeTitle || "leaderboard"}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ----------------------------------------------------------------
// 10. Print / Save-as-PDF — uses the browser's native print dialog
//     on a print-only stylesheet (see index.html). No backend,
//     no PDF library required.
// ----------------------------------------------------------------
function downloadPDF() {
  if (!currentState) return;

  const previousTitle = document.title;
  document.title = `${currentState.assignmentTitle} — Leaderboard`;

  window.print();

  // Restore the tab title after the print dialog closes.
  window.setTimeout(() => {
    document.title = previousTitle;
  }, 500);
}

// ----------------------------------------------------------------
// 11. Init
// ----------------------------------------------------------------
if (typeof document !== "undefined") {
  document.addEventListener("DOMContentLoaded", () => {
    initAssignmentSelector();
    document.getElementById("download-csv-btn").addEventListener("click", downloadCSV);
    document.getElementById("download-pdf-btn").addEventListener("click", downloadPDF);
    setDownloadButtonsEnabled(false);
    selectAssignment(DEFAULT_ASSIGNMENT);
  });
}

if (typeof module !== "undefined") module.exports = { orderEntries };
